### PR TITLE
 #170267352 Get all status types

### PR DESCRIPTION
**Pull request by ivymwende**
#### What does this PR do?
Get all trip status types.

#### Description of Task to be completed?

- [X] Add tests
- [X] Add verify token and verify email validations
- [X] Add status controller function and route

#### How should this be manually tested?
- Clone this repository using the command: `git clone https://github.com/andela/team-odd-bn-backend.git`
- Checkout to this branch using the command: `git checkout ft-get-all-status-functionality-170267352`
- Run the application using the command: `npm run dev-start`
- Run the tests using the command: `npm test`

#### Any background context you want to provide?

Users do not understand what different status ids stand for
so we are creating a route that gets all status types

#### What are the relevant pivotal tracker stories?

[ #170267352](https://www.pivotaltracker.com/story/show/170267352)

#### Screenshots (if appropriate)
image

#### Questions:

### CODE REVIEW

**Review by hezronkimutai — APPROVED** [review]
Nice initiative @ivymwende .

**Review by NiyoEric — APPROVED** [review]
Excellent job @ivymwende!. I think you are good to go!

**Review by william000000 — APPROVED** [review]
Nice Work @ivymwende

**Review by victkarangwa — APPROVED** [review]
Well done!

**Review by shemaeric — APPROVED** [review]
LGTM

**Pull request merged**
