### PR TITLE
#170928329  Display ratings data for each accommodation

### PR DESCRIPTION
**Pull request by NiyongaboEric**
#### What does this PR do?
The PR helps to display ratings for each accommodation.

#### Description of Task to be completed?
**Current**
- Display accommodations only

**Expected**
- Display accommodations with rates

#### How should this be manually tested?
- Clone this repository using the command: `git clone https://github.com/andela/team-odd-bn-backend.git`
- `git clone https://github.com/andela/team-odd-bn-backend.git`
- `cd team-odd-bn-backend`
- git checkout -b ch-add-ratings-170928329 
- `npm install`
- Make sure your `.env` file is updated.
- Drop existing migration `npm run dropTables`
- Update migration `npm run db-migrate`
- Populate the seed data `npm run db-seed-dev`
- `npm run dev-start` check API in development 
- View all accommodations

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#170928329](https://www.pivotaltracker.com/story/show/170928329)

#### Screenshots (if appropriate)

Each accommodation response includes a rating
Screen Shot 2020-01-27 at 19 06 14

### CODE REVIEW

**Review by nziokaivy — APPROVED** [review]
Nice work Eric!

**Review by hezronkimutai — APPROVED** [review]
Nice work.

**Review by victkarangwa — APPROVED** [review]

**Review by hezronkimutai — APPROVED** [review]
Nice initiative

**Review by william000000 — APPROVED** [review]
Looks good!

**Pull request merged**
