### PR TITLE
#170267388  Add get all trip types route

### PR DESCRIPTION
**Pull request by ivymwende**
#### What does this PR do?

Gets all trip types

#### Description of Task to be completed?

- [X] Add tests
- [X] Add verify user's token and verify user validations
- [X] Add get all trip types controller function and route

#### How should this be manually tested?

- Clone this repository using the command: `git clone https://github.com/andela/team-odd-bn-backend.git`
- Checkout to this branch using the command: `git checkout ft-get-triptypes-170267388`
- Run the application using the command: `npm run dev-start`
- Run the tests using the command: `npm test`

#### Any background context you want to provide?

Users do not understand what different trip types ids stand for this reason  we are creating a route that gets all trip types

#### What are the relevant pivotal tracker stories?
[#170267388](https://www.pivotaltracker.com/story/show/170267388)

#### Screenshots (if appropriate)
image

#### Questions:

### CODE REVIEW

**Review by hezronkimutai — APPROVED** [review]
Good job @ivymwende

**Review by NiyoEric — APPROVED** [review]
Well done @ivymwende! You are good to go.

**Review by william000000 — COMMENTED** [review]
Nice Work @ivymwende, However, if you don't mind you can add swagger documentation for it.

**Review by william000000 — APPROVED** [review]

**Review by victkarangwa — APPROVED** [review]
Good job @ivymwende

**Review by victkarangwa — APPROVED** [review]
Good job @ivymwende

**Review by shemaeric — APPROVED** [review]
LGTM

**Pull request merged**
