### PR TITLE
#170793112 modify manager and super admin requests response

### PR DESCRIPTION
**Pull request by victkarangwa**
#### What does this PR do?
This PR modifies manager and super admin's response data
#### Description of Task to be completed?
- modify the response sent by the route that avails requests to the manager
#### How should this be manually tested?
- `git clone https://github.com/andela/team-odd-bn-backend`
- `git checkout bg-joint-table-response-170793112`
- Open postman.
- Sign in as a manager
- use the manager token in the `/trips/requests` and `/trips/requests/:tripRequestId` route.
- Note the format of the data received.
#### Screenshots (if appropriate)
Screen Shot 2020-01-20 at 20 11 20

#### Questions:

### CODE REVIEW

**Review by nziokaivy — APPROVED** [review]
Great work @victorkarangwa4!

**Review by hezronkimutai — APPROVED** [review]
Nice job.

**Review by NiyoEric — APPROVED** [review]
@victorkarangwa4 Nice job!

**Review by william000000 — APPROVED** [review]
Good Job

**Pull request merged**
