### PR TITLE
#169258656  Notification for creating comment and editing trip request

### PR DESCRIPTION
**Pull request by NiyoEric**
#### What does this PR do?
The PR helps us to send a notification when the user edit trip requests to a manager. Also, it sends a notification when new comment added.

#### Description of Task to be completed?
As a requester, I should be able to see notifications when comments are posted on my request.
As a manager, I should be able to see notifications when a travel request is edited.
So I can determine the next line of action

#### How should this be manually tested?
- Open your terminal
- `git clone https://github.com/andela/team-odd-bn-backend.git`
- `cd team-odd-bn-backend`
- `git checkout ft-notification-structure-169258656`
- Make sure your `.env` file is updated.
- Run migrations `npm run db-migrate`
- Run `psql`  ([Download](https://www.postgresql.org/download/) if it's not installed)
- Run `\c barefoot_nomad_test_db` to connect to the database
- Run `SELECT * FROM {tableName}`
- OR `select * from INFORMATION_SCHEMA.TABLE_CONSTRAINTS;` to see the schema

#### Any background context you want to provide?
The Two routes had already been implemented. they are used to send a notification before returning a response to a user.

``` js
# Edit trip request 
PUT URL/api/v1/trips/edit/{tripRequestsId}

# Add new comment
POST URL/api/v1/trips/{tripRequestsId}/comment
```

#### What are the relevant pivotal tracker stories?
[#169258656](https://www.pivotaltracker.com/story/show/169258656)
#### Screenshots (if appropriate)

Send notification when new comment added
Screen Shot 2019-12-10 at 19 13 53

Send notification when user edit trip request
Screen Shot 2019-12-10 at 19 15 17

#### Questions:

### CODE REVIEW

**Review by victkarangwa — APPROVED** [review]
Well done @NiyoEric

**Review by hezronkimutai — APPROVED** [review]
Good work @NiyoEric

**Review by ivymwende — APPROVED** [review]
Great job @NiyoEric I love how you made the function for sending notifications reusable!
Well Done!

**Review by julietezekwe — APPROVED** [review]
LGTM

**Pull request merged**
