### PR TITLE
#171177423 A user should be able to create similar trips but with different start and return dates 

### PR DESCRIPTION
**Pull request by hezronkimutai**
#### What does this PR do?
This PR fixes trip request validations by removing a validation that hinders users to create a request with same origin and destination but different dates
#### Description of Task to be completed?
- This PR fixes a bug in the trip request validations by removing middleware that prevented users to create a trip with same origin and destination but at different times. 
#### How should this be manually tested?
- git clone `https://github.com/andela/team-odd-bn-backend`
- git checkout `bg-fix-multicity-validations-171177423`
- To run the tests, `npm run test`
- to run the application `npm run dev-start`
#### Any background context you want to provide?
- I just removed the middleware call  from the routes but did not delete the actual middleware. I did this so that instead we need the middleware in the future we can just call it.
#### Questions:

### CODE REVIEW

**Review by NiyoEric — COMMENTED** [review]
So far so good @hezronkimutai! Also consider implementing all feedback requested during the pre-demo.

**Review by NiyoEric — APPROVED** [review]
Good job @hezronkimutai! You are good to go.

**Review by victkarangwa — APPROVED** [review]
Nice work @hezronkimutai

**Review by victkarangwa — APPROVED** [review]

**Review by william000000 — APPROVED** [review]
@hezronkimutai, Nice Work!

**Pull request merged**
